version: '3.8'

services:
  # PostgreSQL service
  payment-postgres:
    image: postgres:latest
    container_name: payment-postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "7432:${POSTGRES_PORT}"  # Load PostgreSQL port from .env
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent volume for PostgreSQL data
    networks:
      - payment-network  # Connect to the custom network

  # payment App (NestJS) service
  payment-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-app
    command: sh -c "npm run start:dev"
    ports:
      - "${APP_PORT}:3003"  # Map port 3002 on the host to port 3002 in the container
    environment:
      POSTGRES_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@payment-postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    depends_on:
      - payment-postgres  # Ensure PostgreSQL starts first
    networks:
      - payment-network  # Connect to the custom network

volumes:
  postgres-data:  # Volume for PostgreSQL data

networks:
  payment-network:
    driver: bridge  # Custom Docker network
