version: '3.8'

services:
  inventory-service:
    container_name: inventory-service
    build:
      context: .
    command: sh -c "if [ \"$NODE_ENV\" = \"production\" ]; then npm start; else npm run start:dev; fi"
    ports:
      - "${APP_PORT}:${APP_PORT}" # Expose application port
      - "${APP_DEBUG_PORT}:9229" # Debugging port in development
    networks:
      - inventory-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV}
      APP_PORT: ${APP_PORT}
      APP_DEBUG_PORT: ${APP_DEBUG_PORT}
      MONGO_URI: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: mongodb-inventory
    command: mongod --port ${MONGO_PORT:-27017}
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      TZ: 'Asia/Dhaka'
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    networks:
      - inventory-network
    restart: always

networks:
  inventory-network:
    driver: bridge
